name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.21.0
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.0"
        id: go

      - name: Run Acceptance Tests
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: make testacc
